In [ ]:
import pandas as pd

# Load data from Excel into a Pandas DataFrame
file_path = '/content/omega_cleaned.csv'  # Adjust the path as per your file location
df = pd.read_csv(file_path)

In [ ]:
df.head(20)

,Value Date,ChequeNo.,Description,Debit,Credit,Available Balance(INR),classification
0,27/02/2021,-,NEFT-N058211420157383-MURUGESAN C-LUKER-\n5020...,NaN,"1,00,000.00","-1,50,22,281.05",Income
1,27/02/2021,-,MMT/IMPS/105809933588/7k/N ASHOK KU to SHREE SAPT,NaN,7000,"-1,50,15,281.05",Income
2,28/02/2021,-,MMT/IMPS/105916313747/SELVAKUMAR/Canara Bank,NaN,50000,"-1,49,65,281.05",Income
3,28/02/2021,-,NEFT-SBIN421059077319-AVR SWARNA MAHAL JEWELRY...,NaN,37085,"-1,49,28,196.05",Income
4,28/02/2021,-,NEFT-CIUBH21059004611-EDAPPADI MURUGAPPA\nENTE...,NaN,10000,"-1,49,18,196.05",Income
5,01/03/2021,-,UPI/106009173923/UPI/srinivasan27rs@/State Ban...,NaN,10000,"-1,49,08,196.05",Income
6,01/03/2021,-,BY CASH - SALEM - AGRAHARAM STREET,NaN,"4,95,000.00","-1,44,13,196.05",Income
7,01/03/2021,-,CLG/S K ENTERPRISES/166577/AXI/26.02.2021,NaN,31578,"-1,43,81,618.05",Income
8,01/03/2021,-,CLG/G M ENTERPRISES/544512/SYB/26.02.2021,NaN,25077,"-1,43,56,541.05",Income
9,01/03/2021,-,CLG/ARROW VENTURES/090886/AXI/25.02.2021,NaN,11231,"-1,43,45,310.05",Income
10,01/03/2021,-,NEFT-N060210079338804-GALAXY 7 CO-1622-\n162...,NaN,2300,"-1,43,43,010.05",Income
11,01/03/2021,5364,CLG/TUBES AND PIPES/HDF,14930,NaN,"-1,43,57,940.05",Expense
12,01/03/2021,5341,CLG/SRI MURUGAPPA ELECTRICALS/INB,7582,NaN,"-1,43,65,522.05",Expense
13,01/03/2021,-,NEFT-N060210079349405-RM SPINNING MILLS-- 1667...,NaN,10752,"-1,43,54,770.05",Income
14,01/03/2021,5485,CLG/MAHESH PIPE CENTRE/HDF,65717,NaN,"-1,44,20,487.05",Expense
15,01/03/2021,5529,CLG/MAHALAXMI AGENCIES/TMB,54048,NaN,"-1,44,74,535.05",Expense
16,01/03/2021,-,BY CASH - SALEM - AGRAHARAM STREET,NaN,"2,60,000.00","-1,42,14,535.05",Income
17,01/03/2021,5047,TRFR TO:METALS AND METAL(ELECTRIC)PVT LTD,50000,NaN,"-1,42,64,535.05",Expense
18,01/03/2021,5371,NEFT:000102252429/BARB0VJVAST/VISHWAS TRADING\...,40736,NaN,"-1,43,05,271.05",Expense
19,01/03/2021,-,TRFR FROM: S SINGARAVEL,NaN,60000,"-1,42,45,271.05",Income

In [ ]:
  #column_to_drop = 'Unnamed: 5'
  #if column_to_drop in df.columns:
    #  df.drop([column_to_drop], axis=1, inplace=True)
     # print(f"Column '{column_to_drop}' dropped successfully.")
  #else:
   #   print(f"Column '{column_to_drop}' not found in the DataFrame.")

  #df.head()

In [ ]:
df['classification'] = df['classification'].map({'Expense': 0, 'Income': 1})

In [ ]:
df['Description'] = df['Description'].astype(str)

In [ ]:
df['Description'].dtype

dtype('O')

In [ ]:
df.head(15)

,Value Date,ChequeNo.,Description,Debit,Credit,Available Balance(INR),classification
0,27/02/2021,-,NEFT-N058211420157383-MURUGESAN C-LUKER-\n5020...,NaN,"1,00,000.00","-1,50,22,281.05",1
1,27/02/2021,-,MMT/IMPS/105809933588/7k/N ASHOK KU to SHREE SAPT,NaN,7000,"-1,50,15,281.05",1
2,28/02/2021,-,MMT/IMPS/105916313747/SELVAKUMAR/Canara Bank,NaN,50000,"-1,49,65,281.05",1
3,28/02/2021,-,NEFT-SBIN421059077319-AVR SWARNA MAHAL JEWELRY...,NaN,37085,"-1,49,28,196.05",1
4,28/02/2021,-,NEFT-CIUBH21059004611-EDAPPADI MURUGAPPA\nENTE...,NaN,10000,"-1,49,18,196.05",1
5,01/03/2021,-,UPI/106009173923/UPI/srinivasan27rs@/State Ban...,NaN,10000,"-1,49,08,196.05",1
6,01/03/2021,-,BY CASH - SALEM - AGRAHARAM STREET,NaN,"4,95,000.00","-1,44,13,196.05",1
7,01/03/2021,-,CLG/S K ENTERPRISES/166577/AXI/26.02.2021,NaN,31578,"-1,43,81,618.05",1
8,01/03/2021,-,CLG/G M ENTERPRISES/544512/SYB/26.02.2021,NaN,25077,"-1,43,56,541.05",1
9,01/03/2021,-,CLG/ARROW VENTURES/090886/AXI/25.02.2021,NaN,11231,"-1,43,45,310.05",1
10,01/03/2021,-,NEFT-N060210079338804-GALAXY 7 CO-1622-\n162...,NaN,2300,"-1,43,43,010.05",1
11,01/03/2021,5364,CLG/TUBES AND PIPES/HDF,14930,NaN,"-1,43,57,940.05",0
12,01/03/2021,5341,CLG/SRI MURUGAPPA ELECTRICALS/INB,7582,NaN,"-1,43,65,522.05",0
13,01/03/2021,-,NEFT-N060210079349405-RM SPINNING MILLS-- 1667...,NaN,10752,"-1,43,54,770.05",1
14,01/03/2021,5485,CLG/MAHESH PIPE CENTRE/HDF,65717,NaN,"-1,44,20,487.05",0

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
import torch
from transformers import TrainingArguments, Trainer
from transformers import BertTokenizer, BertForSequenceClassification

In [ ]:
from transformers import BertTokenizer, BertForSequenceClassification
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForSequenceClassification.from_pretrained('bert-base-uncased',num_labels=2)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
model = model.to('cuda')

In [ ]:
X = list(df["Description"])
y = list(df["classification"])
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)
X_train_tokenized = tokenizer(X_train, padding=True, truncation=True, max_length=512)
X_val_tokenized = tokenizer(X_val, padding=True, truncation=True, max_length=512)

In [ ]:
len(X_train),len(X_val)

(15862, 3966)

In [ ]:
class Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels=None):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        if self.labels is not None:
            item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

    def __len__(self):
        return len(self.encodings["input_ids"])

In [ ]:
train_dataset = Dataset(X_train_tokenized, y_train)
val_dataset = Dataset(X_val_tokenized, y_val)

In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

In [ ]:
def compute_metrics(p):
    print(type(p))
    pred, labels = p
    pred = np.argmax(pred, axis=1)

    accuracy = accuracy_score(y_true=labels, y_pred=pred)
    recall = recall_score(y_true=labels, y_pred=pred)
    precision = precision_score(y_true=labels, y_pred=pred)
    f1 = f1_score(y_true=labels, y_pred=pred)

    return {"accuracy": accuracy, "precision": precision, "recall": recall, "f1": f1}

In [ ]:
#!pip install transformers datasets
import torch
from transformers import AutoModelForSequenceClassification

# Assuming your model is named 'model'
num_labels = 2 # Assuming you want a single output value
model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=num_labels)

# Add a linear layer
classifier = torch.nn.Linear(model.config.hidden_size, num_labels) # Create a linear layer
model.classifier = classifier # Replace the existing classifier with the new one

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
args = TrainingArguments(
    output_dir="output",
    num_train_epochs=4,
    per_device_train_batch_size=1

)
trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

In [ ]:
from transformers import TrainingArguments, Trainer

args = TrainingArguments(
    output_dir="output",
    num_train_epochs=4,
    per_device_train_batch_size=1,
    learning_rate=5e-5,  # Set the learning rate here
    weight_decay=0.01,  # Optional: Add weight decay if needed
    logging_dir='./logs',  # Optional: Directory for storing logs
    logging_steps=500,  # Optional: Frequency of logging
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

In [ ]:
trainer.train()

RuntimeError: [enforce fail at inline_container.cc:595] . unexpected pos 52096 vs 51988

In [ ]:
trainer.evaluate()

In [ ]:
from transformers import Trainer

# Define the directory where you want to save your fine-tuned model
output_dir = "bsa"

# Save the fine-tuned model
trainer.save_model(output_dir)
tokenizer.save_pretrained(output_dir)

print(f"Fine-tuned model and tokenizer saved to {output_dir}")

In [ ]:
from transformers import BertTokenizer, BertForSequenceClassification

# Load the saved model and tokenizer
model_path = '/content/bsa'
model = BertForSequenceClassification.from_pretrained(model_path)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [ ]:
inputs = tokenizer(df['Description'].tolist(), padding=True, truncation=True, max_length=512, return_tensors='pt')

In [ ]:
import torch

model.eval()
with torch.no_grad():
    outputs = model(**inputs)
    predictions = torch.argmax(outputs.logits, dim=-1)

# Map predictions to labels
predictions = predictions.numpy()
df['Classification'] = ['Income' if pred == 1 else 'Expense' for pred in predictions]

In [ ]:
print(df)

In [ ]:
text = "withdraw amount"
# text = "go to hell"
inputs = tokenizer(text,padding = True, truncation = True, return_tensors='pt').to('cuda')
outputs = model(**inputs)
print(outputs)
predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
print(predictions)
predictions = predictions.cpu().detach().numpy()
predictions